format_version: 10
pipelines:
  demo2:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-bc553df:
        git: https://github.com/sohamm-coditas/python-hello.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                - -r
                - requirements.txt
                command: pip3
                run_if: passed
            - exec:
                arguments:
                - server.py
                command: python3
                run_if: passed
