format_version: 10
pipelines:
  MyFirstPipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-69baad8:
        git: https://github.com/samohite09/python-hello
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          HelloWorld:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello, World!
                command: echo
                run_if: passed
