format_version: 10
pipelines:
  hello-world-pipeline:
    group: sample-pipelines
    materials:
      git-repo: https://github.com/samohite09/python-hello.git
      branch: main
    stages:
      - name: build
        jobs:
          - name: display-hello-world
            tasks:
              - exec:
                  command: echo "Hello, World!"
